/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.WelcomeController;
import dao.AccessBackofficeDAO;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import model.AccessBackoffice;

/**
 *
 * @author Formation
 */
public class InitialisationView extends javax.swing.JDialog {
    AccessBackoffice accessBack = new AccessBackoffice();
    AccessBackofficeDAO accessBackDAO = new AccessBackofficeDAO();
    
    WelcomeController welcomeController;
    /**
     * Creates new form InitialisationView
     */
    public InitialisationView(java.awt.Frame parent, boolean modal,WelcomeController welcomeController) {
        super(parent, modal);
        initComponents();
        this.welcomeController=welcomeController;
    }

    InitialisationView() {
        }

    private InitialisationView(JFrame jFrame, boolean b) {
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pb_confirm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_newMDP = new javax.swing.JPasswordField();
        tf_confirmMDP = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Initialisation");
        setMinimumSize(new java.awt.Dimension(451, 542));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pb_confirm.setText("Confirmer");
        pb_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pb_confirmActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(pb_confirm, gridBagConstraints);

        jLabel1.setText("Nouveau mot de passe");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(27, 13, 27, 13);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Confirmer le mort de passe");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(27, 13, 27, 13);
        getContentPane().add(jLabel2, gridBagConstraints);

        tf_newMDP.setMaximumSize(new java.awt.Dimension(125, 25));
        tf_newMDP.setMinimumSize(new java.awt.Dimension(125, 25));
        tf_newMDP.setPreferredSize(new java.awt.Dimension(125, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(27, 13, 27, 13);
        getContentPane().add(tf_newMDP, gridBagConstraints);

        tf_confirmMDP.setMaximumSize(new java.awt.Dimension(125, 25));
        tf_confirmMDP.setMinimumSize(new java.awt.Dimension(125, 25));
        tf_confirmMDP.setPreferredSize(new java.awt.Dimension(125, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(27, 13, 27, 13);
        getContentPane().add(tf_confirmMDP, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pb_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pb_confirmActionPerformed
                    this.welcomeController.currentUserHasChanged(this);

    }//GEN-LAST:event_pb_confirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitialisationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitialisationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitialisationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitialisationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InitialisationView dialog = new InitialisationView(new javax.swing.JFrame(), true,new WelcomeController());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JButton getPb_confirm() {
        return pb_confirm;
    }

    public JPasswordField getTf_confirmMDP() {
        return tf_confirmMDP;
    }

    public JPasswordField getTf_newMDP() {
        return tf_newMDP;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton pb_confirm;
    private javax.swing.JPasswordField tf_confirmMDP;
    private javax.swing.JPasswordField tf_newMDP;
    // End of variables declaration//GEN-END:variables
}
