/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.NewUserController;
import dao.UserDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Formation
 */

public class NewUserView extends javax.swing.JPanel {

    /**
     * Creates new form NewUserView
     */
    
    private NewUserController newUserController;
            
//------------------------------------------------------------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lb_title = new javax.swing.JLabel();
        lb_pseudo = new javax.swing.JLabel();
        tf_pseudo = new javax.swing.JTextField();
        lb_password = new javax.swing.JLabel();
        pf_password = new javax.swing.JPasswordField();
        lb_firstname = new javax.swing.JLabel();
        tf_firstname = new javax.swing.JTextField();
        lb_lastname = new javax.swing.JLabel();
        tf_lastname = new javax.swing.JTextField();
        lb_mail = new javax.swing.JLabel();
        tf_mail = new javax.swing.JTextField();
        lb_tel = new javax.swing.JLabel();
        tf_tel = new javax.swing.JTextField();
        lb_address = new javax.swing.JLabel();
        tf_address = new javax.swing.JTextField();
        lb_city = new javax.swing.JLabel();
        tf_city = new javax.swing.JTextField();
        lb_country = new javax.swing.JLabel();
        tf_country = new javax.swing.JTextField();
        lb_function = new javax.swing.JLabel();
        cb_admin = new javax.swing.JCheckBox();
        bt_create = new javax.swing.JButton();
        cb_function = new javax.swing.JComboBox<>();
        bt_cancel = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jLabel3.setText("jLabel3");

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setLayout(new java.awt.GridBagLayout());

        lb_title.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lb_title.setText("Nouvel Utilisateur");
        lb_title.setMaximumSize(new java.awt.Dimension(200, 22));
        lb_title.setMinimumSize(new java.awt.Dimension(200, 22));
        lb_title.setPreferredSize(new java.awt.Dimension(200, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 6, 0);
        add(lb_title, gridBagConstraints);

        lb_pseudo.setText("pseudo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        add(lb_pseudo, gridBagConstraints);

        tf_pseudo.setMaximumSize(new java.awt.Dimension(150, 20));
        tf_pseudo.setMinimumSize(new java.awt.Dimension(150, 20));
        tf_pseudo.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 0);
        add(tf_pseudo, gridBagConstraints);

        lb_password.setText("mot de passe");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        add(lb_password, gridBagConstraints);

        pf_password.setMaximumSize(new java.awt.Dimension(150, 20));
        pf_password.setMinimumSize(new java.awt.Dimension(150, 20));
        pf_password.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 0);
        add(pf_password, gridBagConstraints);

        lb_firstname.setText("prenom");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        add(lb_firstname, gridBagConstraints);

        tf_firstname.setMaximumSize(new java.awt.Dimension(150, 20));
        tf_firstname.setMinimumSize(new java.awt.Dimension(150, 20));
        tf_firstname.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 0);
        add(tf_firstname, gridBagConstraints);

        lb_lastname.setText("nom");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        add(lb_lastname, gridBagConstraints);

        tf_lastname.setMaximumSize(new java.awt.Dimension(150, 20));
        tf_lastname.setMinimumSize(new java.awt.Dimension(150, 20));
        tf_lastname.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 0);
        add(tf_lastname, gridBagConstraints);

        lb_mail.setText("mail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        add(lb_mail, gridBagConstraints);

        tf_mail.setMaximumSize(new java.awt.Dimension(150, 20));
        tf_mail.setMinimumSize(new java.awt.Dimension(150, 20));
        tf_mail.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 0);
        add(tf_mail, gridBagConstraints);

        lb_tel.setText("tel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        add(lb_tel, gridBagConstraints);

        tf_tel.setMaximumSize(new java.awt.Dimension(150, 20));
        tf_tel.setMinimumSize(new java.awt.Dimension(150, 20));
        tf_tel.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 0);
        add(tf_tel, gridBagConstraints);

        lb_address.setText("adresse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        add(lb_address, gridBagConstraints);

        tf_address.setMaximumSize(new java.awt.Dimension(150, 20));
        tf_address.setMinimumSize(new java.awt.Dimension(150, 20));
        tf_address.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 0);
        add(tf_address, gridBagConstraints);

        lb_city.setText("ville");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        add(lb_city, gridBagConstraints);

        tf_city.setMaximumSize(new java.awt.Dimension(150, 20));
        tf_city.setMinimumSize(new java.awt.Dimension(150, 20));
        tf_city.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 0);
        add(tf_city, gridBagConstraints);

        lb_country.setText("pays");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        add(lb_country, gridBagConstraints);

        tf_country.setMaximumSize(new java.awt.Dimension(150, 20));
        tf_country.setMinimumSize(new java.awt.Dimension(150, 20));
        tf_country.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 0);
        add(tf_country, gridBagConstraints);

        lb_function.setText("fonction");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        add(lb_function, gridBagConstraints);

        cb_admin.setText("administrateur");
        cb_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_adminActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 60, 6, 0);
        add(cb_admin, gridBagConstraints);

        bt_create.setText("creer");
        bt_create.setMaximumSize(new java.awt.Dimension(100, 25));
        bt_create.setMinimumSize(new java.awt.Dimension(100, 25));
        bt_create.setPreferredSize(new java.awt.Dimension(100, 25));
        bt_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_createActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        add(bt_create, gridBagConstraints);

        cb_function.setMaximumSize(new java.awt.Dimension(150, 20));
        cb_function.setMinimumSize(new java.awt.Dimension(150, 20));
        cb_function.setPreferredSize(new java.awt.Dimension(150, 20));
        cb_function.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_functionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 0);
        add(cb_function, gridBagConstraints);

        bt_cancel.setText("annuler");
        bt_cancel.setMaximumSize(new java.awt.Dimension(100, 25));
        bt_cancel.setMinimumSize(new java.awt.Dimension(100, 25));
        bt_cancel.setPreferredSize(new java.awt.Dimension(100, 25));
        bt_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(6, 50, 6, 0);
        add(bt_cancel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

//------------------------------------------------------------------------------
    //button create user
    private void bt_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_createActionPerformed

   boolean result = newUserController.CreateNewUser(this);
   
   // if all complete
   if(result){
        
        
        JOptionPane info = new JOptionPane();
        
        info.showMessageDialog(this, 
                "l'utilisateur est créé",
                "information",
                JOptionPane.WARNING_MESSAGE);
   }else{
        
    // if a field is empty    
        JOptionPane alert = new JOptionPane();
    
        alert.showMessageDialog(this,
        "Un champ de creation n'est pas rempli",
        "attention",
        JOptionPane.WARNING_MESSAGE);
   }
    
    }//GEN-LAST:event_bt_createActionPerformed
    
//------------------------------------------------------------------------------
    //empty input 
    private void bt_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelActionPerformed
       
    tf_pseudo.setText("");
    pf_password.setText("");
    tf_firstname.setText("");
    tf_lastname.setText("");
    tf_mail.setText("");
    tf_tel.setText("");
    tf_address.setText("");
    tf_city.setText("");
    tf_country.setText("");
    cb_admin.setSelected(false);
    
    }//GEN-LAST:event_bt_cancelActionPerformed

    private void cb_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_adminActionPerformed

    }//GEN-LAST:event_cb_adminActionPerformed

    private void cb_functionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_functionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_functionActionPerformed

//------------------------------------------------------------------------------
    //use the Jframe
    
    public NewUserView(NewUserController newUserController) {
        initComponents();
        UserDAO userDAO = new UserDAO();
        
        this.newUserController = new NewUserController(userDAO);
        
        ArrayList<String> listFunctions = this.newUserController.addComboBox();
        
        for(String function: listFunctions) {
            cb_function.addItem(function);
        }
    }
 
//------------------------------------------------------------------------------
    // fields getters
    
    public JTextField getjTextField1() {
        return jTextField1;
    }

    public JPasswordField getPf_password() {
        return pf_password;
    }

    public JTextField getTf_address() {
        return tf_address;
    }

    public JTextField getTf_city() {
        return tf_city;
    }

    public JTextField getTf_country() {
        return tf_country;
    }

    public JTextField getTf_firstname() {
        return tf_firstname;
    }

    public JTextField getTf_lastname() {
        return tf_lastname;
    }

    public JTextField getTf_mail() {
        return tf_mail;
    }

    public JTextField getTf_pseudo() {
        return tf_pseudo;
    }

    public JTextField getTf_tel() {
        return tf_tel;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancel;
    private javax.swing.JButton bt_create;
    private javax.swing.JCheckBox cb_admin;
    private javax.swing.JComboBox<String> cb_function;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lb_address;
    private javax.swing.JLabel lb_city;
    private javax.swing.JLabel lb_country;
    private javax.swing.JLabel lb_firstname;
    private javax.swing.JLabel lb_function;
    private javax.swing.JLabel lb_lastname;
    private javax.swing.JLabel lb_mail;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel lb_pseudo;
    private javax.swing.JLabel lb_tel;
    private javax.swing.JLabel lb_title;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JTextField tf_address;
    private javax.swing.JTextField tf_city;
    private javax.swing.JTextField tf_country;
    private javax.swing.JTextField tf_firstname;
    private javax.swing.JTextField tf_lastname;
    private javax.swing.JTextField tf_mail;
    private javax.swing.JTextField tf_pseudo;
    private javax.swing.JTextField tf_tel;
    // End of variables declaration//GEN-END:variables
}