/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.WelcomeController;
import dao.AccessBackofficeDAO;

import model.AccessBackoffice;

import view.InitialisationView;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Formation
 */
public class WelcomeView extends java.awt.Dialog {

    AccessBackoffice accessBack = new AccessBackoffice();
    AccessBackofficeDAO accessBackDAO = new AccessBackofficeDAO();
    int nombreDessaiMDP = 3;
    WelcomeController welcomeController;

    /**
     * Creates new form WelcomeView
     */
    public WelcomeView(java.awt.Frame parent, boolean modal, WelcomeController welcomeController) {
        super(parent, modal);
        initComponents();
        this.welcomeController = welcomeController;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Nickname = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        tf_nickname = new javax.swing.JTextField();
        pb_Connexion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_password = new javax.swing.JPasswordField();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        setTitle("Welcome");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        Nickname.setText("Nickname");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(Nickname, gridBagConstraints);

        Password.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(Password, gridBagConstraints);

        tf_nickname.setMaximumSize(new java.awt.Dimension(125, 25));
        tf_nickname.setMinimumSize(new java.awt.Dimension(125, 25));
        tf_nickname.setPreferredSize(new java.awt.Dimension(125, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(19, 22, 19, 21);
        add(tf_nickname, gridBagConstraints);

        pb_Connexion.setText("Connection");
        pb_Connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pb_ConnexionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(32, 0, 32, 0);
        add(pb_Connexion, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 25);
        add(jLabel2, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 25);
        add(jLabel3, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Welcome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(63, 0, 63, 0);
        add(jLabel1, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("© DEV-FLY 2013 - Site web http://dev-fly.fr");
        jLabel4.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(42, 0, 42, 0);
        add(jLabel4, gridBagConstraints);

        tf_password.setMaximumSize(new java.awt.Dimension(125, 25));
        tf_password.setMinimumSize(new java.awt.Dimension(125, 25));
        tf_password.setPreferredSize(new java.awt.Dimension(125, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(tf_password, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void pb_ConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pb_ConnexionActionPerformed

        InitialisationView initView = new InitialisationView(null, true, welcomeController);
        this.welcomeController.testIdentifying(this, initView);

    }//GEN-LAST:event_pb_ConnexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WelcomeView dialog = new WelcomeView(new java.awt.Frame(), true, new WelcomeController());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JTextField getTf_nickname() {
        return tf_nickname;
    }

    public JPasswordField getTf_password() {
        return tf_password;
    }

    public int getNombreDessaiMDP() {
        return nombreDessaiMDP;
    }

    public JButton getPb_Connexion() {
        return pb_Connexion;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nickname;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton pb_Connexion;
    private javax.swing.JTextField tf_nickname;
    private javax.swing.JPasswordField tf_password;
    // End of variables declaration//GEN-END:variables
}
